version: '3.8'

services:
  agent:
    build: .
    container_name: agent-api
    ports:
      - "8080:8080"
    environment:
      - TOOL_MANAGER_URL=http://tool-manager:8000
      - OLLAMA_BASE_URL=http://ollama:11434
      - DEFAULT_MODEL=gemma3
      - ENVIRONMENT=production
    depends_on:
      - ollama
      - tool-manager
    networks:
      - agent-network
    restart: unless-stopped

  tool-manager:
    image: tool-manager-api:latest  # You need to build this image separately
    container_name: tool-manager-api
    ports:
      - "8000:8000"
    networks:
      - agent-network
    volumes:
      - tool-manager-data:/app/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - agent-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  agent-network:
    driver: bridge

volumes:
  tool-manager-data:
  ollama-data: 